name: Build image manifests

on:
  push:
    branches: ["**"]          # so preview branches get manifests too
    paths:
      - "images/**"
      - "scripts/**"
      - ".github/workflows/manifests.yml"
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate manifests
        run: node scripts/generate-manifests.mjs

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add images/memes/manifest.json images/examples/manifest.json
            git commit -m "chore: update image manifests"
            git push
          else
            echo "No changes to commit."
          fi

